### ISSUE TITLE
How to resolve gpg key ?

### ISSUE THREAD

**Issue by Tom-Krnl** [ethpandaops/template-devnets#59]
ansible/inventories/devnet-0/group_vars/all/all.sops.yaml: CouldNotRetrieveKey exited with code 128: Failed to get the data key required to decrypt the SOPS file.

Group 0: FAILED
  80DB2B4EF6CA4D9829C280605636BC0E08138A24: FAILED
    - | could not decrypt data key with PGP key:
      | github.com/ProtonMail/go-crypto/openpgp error: Could not
      | load secring: open /home/tom/.gnupg/secring.gpg: no such
      | file or directory; GPG binary error: exit status 2

  69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD: FAILED
    - | could not decrypt data key with PGP key:
      | github.com/ProtonMail/go-crypto/openpgp error: Could not
      | load secring: open /home/tom/.gnupg/secring.gpg: no such
      | file or directory; GPG binary error: exit status 2

**Comment by barnabasbusa** [comment]
You have to use your own pgp key to encrypt the sops files. Place your own pgp key in the [.sops.yaml](https://github.com/ethpandaops/template-devnets/blob/master/.sops.yaml) file and re-encrypt all sops with:

https://github.com/ethpandaops/template-devnets/blob/master/README.md?plain=1#L145
